### ISSUE TITLE
Add levels

### ISSUE THREAD

**Issue by ZeroAT** [jameno/supercold#3]
Other than the "Continuous" game mode, we would need 5-10 levels that introduce new obstacles/challenges.

**Comment by jameno** [comment]
This includes creating a "campaign" and "survival" button on the main menu. The coin collection on each campaign level will call a function that clears the page and loads the next level. I think each level can be represented by a single vector with all the relevant information: [player starting position, array with enemy starting positions, array with obstacle positions and sizes, coin position].

**Comment by ZeroAT** [comment]
Added levels 2 and 3 so far.
